### ISSUE TITLE
merge of gpu branches and master

### ISSUE THREAD

**Issue by lifengjin** [tmills/uhhmm#43]
I have merged the GPU branches: uhhmm-c and osc to the master. Just open this as a place to report if anything is broken by the merge in the CPU version of the code.

**Comment by vkrakovna** [comment]
I was unable to run the CPU version because of the dependency
on CHmmSampler in PyzmqWorker.pyx - this should be imported in the GPU
branch of the if statement on line 99 (fixed by my latest commit).

I spent a few hours trying to get the GPU version to run on the Harvard
cluster, but I'm getting a ton of compile errors when sourcing
./gpusrc/compile_linux.sh. I think I'll stick to the CPU version.

**Comment by lifengjin** [comment]
Yeah it is always tricky to compile. You can post the errors if you want and I can give you some suggestions of how to compile it.

**Comment by vkrakovna** [comment]
For some of my unit test runs, I am getting exceptions from PyzmqWorker.pyx
(see below). Not sure if it's related to your merge of the GPU version.

EXCEPTION IN (PyzmqWorker.pyx, LINE 80 ""): Ran out of input
Process Process-1:
Traceback (most recent call last):
  File "/n/sw/fasrcsw/apps/Core/Anaconda3/2.1.0-fasrc01/x/lib/
python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/n/sw/fasrcsw/apps/Core/Anaconda3/2.1.0-fasrc01/x/lib/
python3.4/multiprocessing/process.py", line 93, in run
    self._target(_self._args, *_self._kwargs)
  File "PyzmqWorker.pyx", line 83, in PyzmqWorker.PyzmqWorker.run
(scripts/PyzmqWorker.c:2925)
  File "PyzmqWorker.pyx", line 80, in PyzmqWorker.PyzmqWorker.run
(scripts/PyzmqWorker.c:2843)
EOFError: Ran out of input

This comes with lots of debug messages "DEBUG:root:Sending worker a model
in response to signal b'0'"

**Comment by lifengjin** [comment]
This one does not look like it is related to GPU version.
