### ISSUE TITLE
increment_counts incorrectly reads parse

### ISSUE THREAD

**Issue by tmills** [tmills/uhhmm#63]
Got the following error, which seems to think the -/- at token index 2 is a -/+? I'll look into it but if @coryshain has any insight let me know.

```
ERROR:root:This parse is bad:
ERROR:root:The sentence is 13 14 15 16 8
ERROR:root:The state sequence is 1 2300 282 2818 848
ERROR:root:-/-::ACT0/AWA0:POS1 +/-::ACT5/AWA2:POS5 -/-::ACT2/AWA2:POS10 +/+::ACT2/AWA4:POS13 -/+::ACT0/AWA0:POS15
ERROR:root:The index is 2

```

**Comment by coryshain** [comment]
Are you using split merge? If so there's a long-standing bug where the
indexer in the main script doesn't get updated as the model changes, which
will make that error log meaningless because the indexer can't interpret
the state index. We should fix that. Meanwhile, the assert statement from
the error that produced the crash should be more informative, if you happen
to still have it.

On Fri, Mar 24, 2017, 4:03 PM Tim Miller <notifications@github.com> wrote:

Got the following error, which seems to think the -/- at token index 2 is a
-/+? I'll look into it but if @coryshain <https://github.com/coryshain> has
any insight let me know.

ERROR:root:This parse is bad:
ERROR:root:The sentence is 13 14 15 16 8
ERROR:root:The state sequence is 1 2300 282 2818 848
ERROR:root:-/-::ACT0/AWA0:POS1 +/-::ACT5/AWA2:POS5
-/-::ACT2/AWA2:POS10 +/+::ACT2/AWA4:POS13 -/+::ACT0/AWA0:POS15
ERROR:root:The index is 2


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tmills/uhhmm/issues/63>, or mute the thread

**Comment by tmills** [comment]
No split/merge. It happens on the very first parsed batch.

```
Traceback (most recent call last):
  File "/home/tmill/Projects/uhhmm/scripts/uhhmm.py", line 322, in sample_beam
    increment_counts(parse.state_list, ev_seqs[ parse.index ], models, inc)
  File "/home/tmill/Projects/uhhmm/scripts/uhhmm.py", line 702, in increment_counts
    assert depth > 0 or index == len(sent) - 1, "Found a -/+ decision at depth 0 prior to sentence end."
AssertionError: Found a -/+ decision at depth 0 prior to sentence end.

```

**Comment by coryshain** [comment]
Hmm, very weird. I've never seen this before. Is this reproducible? Does it always happen on the same word/sentence?

It has somehow assigned the eos state to the final word of the sentence, which shouldn't be possible. Can you post your config settings so I can see if I can repro?

**Comment by tmills** [comment]
Seems to happen reliably on the first batch of sentences, though not always on the same sentence.

Tried a run with cpu workers only and it got through several iterations. I'll try re-compiling all the gpu code.
 
In the meantime here's my config:

> [io]
> input_file=gendata/simplewiki_d1.tagwords.ints.txt
> output_dir=outputs/debug
> dict_file=gendata/simplewiki_d1.tagwords.dict
> 
> [params]
> ## debugging params -- burnin normally is ~500, num_samples ~ 100, sample_iters ~ 1000
> burnin=20
> num_samples=5
> sample_iters=20
> starta=5
> startb=5
> startg=15
> discount=0
> alphaa=0.5
> alphab=0.5
> alphag=0.5
> alphafj=1.0
> alphah=0.1
> gamma=0.1
> cpu_workers=1
> finite=1
> debug=INFO
> seed=721
> depth=1
> gpu=0
> gpu_workers=0

**Comment by tmills** [comment]
Ah, it looks like a commit commented out the line in the train.sh script that rebuilds the gpu sampler. I had a local fix that didn't quit but just warned that it couldn't compile if it failed. I think this is the root, so I'll try to fix and check in.

**Comment by tmills** [comment]
Yes, that fixes it. I'll fix the train.sh script to not be so severe to cpu users.
